project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/feynlee/pikaQ
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/curiosity_notes
        aria-label: X
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]