# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_utils.ipynb.

# %% auto 0
__all__ = ['quote_symbol', 'to_sql', 'exec']

# %% ../nbs/01_utils.ipynb 2
def quote_symbol(quote):
    """generate quote symbol to use for tables and columns"""
    if type(quote) == str:
        return quote
    else:
        if quote == True:
            return '"'
        else:
            return ''


def to_sql(l):
    if type(l) == list:
        return '(' + ', '.join([f"{item}" if type(item) in (int, float) else f"'{item}'" for item in l]) + ')'
    else:
        raise ValueError(f"type {type(l)} for l is not implemented!")
    return l


def exec(obj, **kwargs):
    """Call the exec method of `obj` if it exists, otherwise return the string representation of `obj`"""
    if hasattr(obj, 'exec'):
        return obj.exec(**kwargs)
    else:
        return obj
